### æœåŠ¡æä¾›è€…å‘eureka serveræ³¨å†Œçš„é…ç½?

spring:
  application:
    name: user-provider #æ³¨å†Œåˆ°eureka serverä¸Šçš„åº”ç”¨åï¼Œæˆ‘è¿™é‡Œä½¿ç”¨çš„æ˜¯artifactId
  cloud:
    service-registry:
      auto-registration:
        enabled: true  #å°†æœåŠ¡æ³¨å†Œåˆ°æ³¨å†Œä¸­å¿ƒ é»˜è®¤æ˜¯true
eureka:
  client:
    service-url:
      #å°†åº”ç”¨æ³¨å†Œåˆ°æ³¨å†Œä¸­å¿ƒï¼Œé…ç½®æ³¨å†Œä¸­å¿ƒåœ°å?ï¼ˆä¹Ÿå¯ä»¥é…ç½®ä¸?ä¸ªï¼Œæ³¨å†Œä¸­å¿ƒä¼šåŒæ­¥èŠ‚ç‚¹ï¼Œæœ?å¥½æ˜¯é…ç½®ä¸¤ä¸ªï¼Œé¿å…æç«¯æƒ…å†µï¼ŒèŠ‚ç‚¹åŒæ­¥ä¸äº†ï¼?
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    prefer-ip-address: true #å°†è‡ªå·±ipæ³¨å†Œåˆ°eureka server,é»˜è®¤false,å¦‚æœfalse,è¡¨ç¤ºå°†ç³»ç»Ÿæ‰€åœ¨çš„hostnameæ³¨å†Œåˆ°eureka server